version: '3'
services:
  microservice1:
    build:
      context: ./producer
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      RABBITMQ_HOST: rabbitmq
      # Add other environment variables as needed for microservice1
  microservice2:
    build:
      context: ./consumer
    environment:
      PORT: 4000
      RABBITMQ_HOST: rabbitmq
      # Add other environment variables as needed for microservice2
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
